### PR TITLE
Fix issue #1 : New approach to load standard library in global scope

### PR DESCRIPTION
**Pull request by trinnguyen**

### CODE REVIEW

**Comment by trinnguyen** [comment]
Fixed this issue: https://github.com/trinnguyen/bahndsl/issues/1

**Comment by trinnguyen** [comment]
@eyip002 This solve the problem with Bahn IDE having validation errors when close/open/close/open project.

**Comment by eyip002** [comment]
> @eyip002 This solve the problem with Bahn IDE having validation errors when close/open/close/open project.

Nice! How do we fix the failing test cases?

**Comment by trinnguyen** [comment]
@eyip002 I am still debugging the test to see what goes wrong with the linker and fix it. However, the Bahn IDE and bahnc work with the new approach.

Now we have a setup in which the standardlib is treated as another bahn model with proper uri. Xtext supports loading source file from this uri scheme: `classpath:/standardlib.bahn` if we put the `standardlib.bahn` in the `resources` folder.

This works out-of-the-box with Bahn IDE (Eclipse) and bahnc. Main changes here:
- https://github.com/trinnguyen/bahndsl/blob/fix-linker/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/linker/BahnImportURIGlobalScopeProvider.java
- https://github.com/trinnguyen/bahndsl/blob/fix-linker/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/generator/StandardLibHelper.java

So our linker should always have 2 Xtext resources in the resource set for resolving scope. The main reason of the failed test is about missing the standardlib resource.

I am working on fixing this first, and will look at the issue of hanging on VSCode, they are somehow related (because of the scope provider).

**Comment by eyip002** [comment]
Fixes the validation bug when opening and closing a BahnDSL project repeatedly.
VSCode extension still hangs after creating artefacts during startup.

**Pull request merged**
