### PR TITLE
Merge the Module-Name export to Yaml

### LINKED ISSUE #54: Export the modulename to the extras-config yaml
As referenced in an issue in [SWTbahn-CLI](https://github.com/uniba-swt/swtbahn-cli/issues/131#issuecomment-2449514587), where we use BahnDSL: It would be very helpful if BahnDSL would export the module name (given in e.g. [this line](https://github.com/trinnguyen/bahndsl/blob/b24a3ab9d7727cdce945435f7c363820c799ac21/examples/standard/SWTbahnStandard.bahn#L1) where the module starts) to the yaml config files somewhere.    
The modulename would serve as an identifier of what platform/model railway is being configured/described in the .bahn file, and would thus be useful in the swtbahn-cli server downstream to know what platform the server is running for/on.

I thought that the "extras-config" yaml file would be a good place to export the module name to. However, we could also consider exporting it to *every* generated yaml file, such that one can check whether they all belong to the same config. But I don't really see that as an important use case, and it would generate more work in implementing the parsers.   
I'll add another comment below with my prototype implementation of how the respective yaml exporter in BahnDSL could be adjusted to export the module name (once that is ready).

### PR DESCRIPTION
**Pull request by BLuedtke**
Closes #54 

Adds the export of the "module-name" to the extras-config.yaml export. Also fixes 2 name convention violations in the extras-config.yaml export (`signaltypes` -> `signal-types` and `peripheraltypes` -> `peripheral-types`) (thanks Eugene!).

Should the version increment/prepare for release happen in this branch before it is merged? Or afterwards somewhere else?

### CODE REVIEW

**Comment by eyip002** [comment]
You could probably update the versioning here.

**Review by eyip002 — APPROVED** [review]

**Comment by BLuedtke** [comment]
> You could probably update the versioning here.

I thought I saw a document somewhere (was it not in this repo?) where it was described in what places the versioning would have to be updated? I guess it is just the pom.xml and the links in the READMEs?

**Comment by BLuedtke** [comment]
I adjusted the version to 1.0.6 in the files I found (except README as of now). I'm unsure about L89 in src/de.uniba.swt.dsl.ide/pom.xml - that looks like its a different plugin that just happens to have version 1.0.5?

**Comment by eyip002** [comment]
> > You could probably update the versioning here.
> 
> I thought I saw a document somewhere (was it not in this repo?) where it was described in what places the versioning would have to be updated? I guess it is just the pom.xml and the links in the READMEs?
> 
> Edit: A I see, in the build.gradle there's a comment what files need to be adjusted.

https://github.com/trinnguyen/bahndsl/wiki/Updating-Version-Number

**Comment by BLuedtke** [comment]
Thanks. Looks like I got all the version tags, will also update the year to 2024 in the plugin xml and BahnIDE product.     
I still have to update and re-generate the splash image. In [the wiki](https://github.com/trinnguyen/bahndsl/wiki/Updating-Splash-Image-and-Launcher-Icon#creating-a-splash-image) it says "Convert the splash image into a 24-bit BMP file. Windows is very sensitive to the formatting of the BMP file!"   -> if Windows is so sensible to this, then how should the conversion be done? Is there a specific tool that is necessary, or does the powerpoint export work somehow (I guess it doesn't?)?

**Review by eyip002 — CHANGES_REQUESTED** [review]
- Update or remove the manually written version number in readme
- Update the splash image.

**Comment by eyip002** [comment]
Perhaps remove:
https://github.com/trinnguyen/bahndsl/blob/bb83047e51a106b90368d30ef93fd8c112111b9f/README.md?plain=1#L11
 

Perhaps simplify by only mentioning the file names, rather than needing to update the links every time a release is made:
https://github.com/trinnguyen/bahndsl/blob/bb83047e51a106b90368d30ef93fd8c112111b9f/README.md?plain=1#L26-L29

**Comment by BLuedtke** [comment]
Powerpoint was not very helpful at all with the bitmap export. Even had to change settings in the Windows Registry regarding powerpoint bitmap export resolution. Currently testing if the new generated splash image works...

**Comment by eyip002** [comment]
I won’t be able to test until next week

**Comment by trinnguyen** [comment]
@BLuedtke I can help with testing on Mac.

**Review by eyip002 — APPROVED** [review]
Just tested the GitHub build artefacts on macOS 15.1.1 and looks okay. Compared to v1.0.5 (which I also just tested again) and noticed some minor things:
- The splash screen is blurrier than before
- The syntax highlighting and diagramming no longer works for SSCharts files (see the screenshot in the readme)
You can decide whether it's worth the effort to fix these cosmetic issues.

**Comment by BLuedtke** [comment]
> Just tested the GitHub build artefacts on macOS 15.1.1 and looks okay. Compared to v1.0.5 (which I also just tested again) and noticed some minor things:
> 
>     * The splash screen is blurrier than before
> 
>     * The syntax highlighting and diagramming no longer works for SSCharts files (see the screenshot in the readme)
>       You can decide whether it's worth the effort to fix these cosmetic issues.

The SCCharts highlighting also doesn't work for me with 1.0.6., it looks like there's no "SCTX Editor" to choose from in the "Open With" menu at all - which is weird, given that all that was changed is not related to what editors are available. I'll see if I find something within half an hour or so, if not then I'd just merge as-is.

**Comment by BLuedtke** [comment]
Adjusting the KlighD update site didn't help (https and/or 2.3.0). I think this kind of problem can be figured out when the next bigger dependency upgrade/management will happen.

**Comment by BLuedtke** [comment]
Ah! Now the question: how do we do a release?

**Comment by eyip002** [comment]
Try following this: https://github.com/trinnguyen/bahndsl/wiki/Creating-a-New-Release#publish-a-new-release

**Pull request merged**
